{
  imports = [
    ./ai.nix
    ./autopairs.nix
    ./comment.nix
    ./conform.nix
    ./escape.nix
    ./fzf-lua.nix
    ./git.nix
    ./hover.nix
    ./neoscroll.nix
    ./oil.nix
    ./surround.nix
    ./snapshots.nix
    ./terminal.nix
    ./trouble.nix
    ./which-key.nix
    ./outline.nix
  ];
}
